doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                server_version: 8.0
        types:
            uuid: App\Shared\Infrastructure\Persistence\Doctrine\MySQL\Type\UuidType


