doctrine_migrations:
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/config/doctrine/migrations'
    enable_profiler: false
    organize_migrations: BY_YEAR
    connection: default
