doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: 'mysql://%env(MYSQL_USERNAME)%:%env(MYSQL_PASSWORD)%@%env(MYSQL_HOST)%:%env(MYSQL_PORT)%/%env(MYSQL_DATABASE_NAME)%'
                server_version: '8.0'
        types:
            uuid: App\Shared\Infrastructure\Persistence\Doctrine\MySQL\Type\UuidType
            name: App\Context\Campaign\Infrastructure\Persistence\Doctrine\MySQL\Type\NameType

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        entity_managers:
            thn:
                connection: default
                validate_xml_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Campaign:
                        type: xml
                        dir: '%kernel.project_dir%/src/Context/Campaign/Infrastructure/Persistence/Doctrine/MySQL/Mapping'
                        prefix: 'App\Context\Campaign\Domain\Write'
                        is_bundle: false
