parameters:
    AMQP_TRANSPORT_DSN: '%env(AMQP_TRANSPORT_DSN)%'

framework:
    messenger:
        default_bus: messenger.bus.events

        buses:
            messenger.bus.events:
                default_middleware: false
                middleware:
                    - dispatch_after_current_bus
                    - thn.shared.application.bus.add_event_bus_name_to_stamp_middleware
                    - thn.shared.infrastructure.bus.event.add_amqp_stamp_middleware
                    - send_message
                    - thn.shared.application.event_bus.handler_middleware

            messenger.bus.commands:
                default_middleware: false
                middleware:
                    - doctrine_ping_connection
                    - dispatch_after_current_bus
                    - thn.shared.application.bus.add_command_bus_name_to_stamp_middleware
                    - thn.shared.application.bus.doctrine_transaction_middleware
                    - handle_message

            messenger.bus.queries:
                default_middleware: false
                middleware:
                    - handle_message

        transports:
            async_domain_event:
                dsn: '%env(AMQP_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: domain_event_exchange
                        type: topic
                    queues:
                        ha_async_domain_event_queue:
                            binding_keys:
                                - 'thn.campaign_manager.domain_event.#'

        routing:
            App\Shared\Domain\Write\Event\DomainEvent: async_domain_event

        serializer:
            default_serializer: App\Shared\Infrastructure\Bus\MessengerMessageSerializer
