parameters:
    AMQP_TRANSPORT_DSN: '%env(AMQP_TRANSPORT_DSN)%'

framework:
    messenger:
        buses:
            messenger.bus.commands:
                default_middleware: false
                middleware:
                    - doctrine_ping_connection
                    - dispatch_after_current_bus
                    - thn.shared.application.bus.add_command_bus_name_to_stamp_middleware
                    - thn.shared.application.bus.doctrine_transaction_middleware
                    - handle_message

        transports:

        routing:

