services:
  nginx:
    image: nginx:alpine
    container_name: nginx_server
    platform: linux/arm64
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  php-fpm:
    container_name: php_fpm
    build:
      dockerfile: docker/php-fpm/Dockerfile
    platform: linux/arm64
    volumes:
      - ./:/var/www/app
      - /var/www/app/var/
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    platform: linux/arm64
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: campaign_manager
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  rabbitmq:
    build: docker/rabbitmq
    container_name: rabbitmq
    ports:
      - "15972:15672"
