health:
    resource: '../src/Shared/UI/Symfony/health.yaml'

campaign:
    resource: '../src/Context/Campaign/UI/Symfony/routes/campaign.yaml'

hotel:
    resource: '../src/Context/Hotel/UI/Symfony/routes/hotel.yaml'

booking:
    resource: '../src/Context/Booking/UI/Symfony/routes/booking.yaml'

metric:
    resource: '../src/Context/Metric/UI/Symfony/routes/metric.yaml'