services:
    _defaults:
        public: true

    _instanceof:
        App\Tests\Fixtures\DataLoader\MySQL\Fixtures:
            tags: [ 'doctrine.fixture.orm' ]

    App\Tests\Acceptance\ApiContext:
        arguments:
            - '@kernel'

    App\Tests\Acceptance\HotelContext:
        arguments:
            - '@kernel'

    test.App\Context\Campaign\Infrastructure\Persistence\Doctrine\MySQL\Repository\DoctrineCampaignRepository: '@App\Context\Campaign\Infrastructure\Persistence\Doctrine\MySQL\Repository\DoctrineCampaignRepository'
    test.App\Context\Hotel\Domain\Write\Repository\HotelRepository: '@App\Context\Hotel\Infrastructure\Persistence\Doctrine\MySQL\Repository\DoctrineHotelRepository'
