services:
    _defaults:
        public: true

    App\Tests\DataFixtures\:
        resource: '../tests/DataFixtures/*'

    _instanceof:
        App\Tests\DataFixtures\DataLoader\MySQL\Fixtures:
            tags: [ 'doctrine.fixture.orm' ]

    doctrine.fixtures.purger.orm_purger_factory:
        class: App\Tests\DataFixtures\Purger\CustomPurgerFactory
        tags:
            - { name: 'doctrine.fixtures.purger_factory', alias: 'default' }

    App\Tests\Acceptance\ApiContext:
        arguments:
            - '@kernel'

    App\Tests\Acceptance\HotelContext:
        arguments:
            - '@kernel'
            - '@test.App\Context\Availability\Domain\Read\Repository\AvailabilityRepository'

    App\Tests\Acceptance\BookingContext:
        arguments:
            - '@kernel'

    test.App\Context\Campaign\Infrastructure\Persistence\Doctrine\MySQL\Repository\DoctrineCampaignRepository: '@App\Context\Campaign\Infrastructure\Persistence\Doctrine\MySQL\Repository\DoctrineCampaignRepository'
    test.App\Context\Hotel\Domain\Write\Repository\HotelRepository: '@App\Context\Hotel\Infrastructure\Write\Persistence\Doctrine\MySQL\Repository\DoctrineHotelRepository'
    test.App\Context\Availability\Domain\Read\Repository\AvailabilityRepository: '@App\Context\Availability\Infrastructure\Persistence\MySQL\Repository\MySQLAvailabilityCalendarRepository'

    App\Tests\DataFixtures\DataLoader\MySQL\AvailabilityFixtures:
        class: App\Tests\DataFixtures\DataLoader\MySQL\AvailabilityFixtures
        arguments:
            - '@test.App\Context\Availability\Domain\Read\Repository\AvailabilityRepository'
