parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $eventBus: '@thn.shared.application.event_bus'
            $commandBus: '@thn.shared.application.command_bus'
            $queryBus: '@thn.shared.application.query_bus'

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    _instanceof:
        # By default, each handler will be available to handle messages on all of your buses.
        # To prevent dispatching a message to the wrong bus without an error,
        # you can restrict each handler to a specific bus using the messenger.message_handler tag:
        App\Shared\Application\Bus\Command\CommandHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: messenger.bus.commands }

        App\Shared\Application\Bus\Query\QueryHandlerInterface:
            tags: [ { name: messenger.message_handler, bus: messenger.bus.queries } ]

        App\Shared\Domain\Message\Message:
            tags: ['message']

    ### Command Bus Configuration ###
    thn.shared.application.command_bus:
        class: App\Shared\Infrastructure\Bus\Command\MessengerCommandBus
        arguments:
            - '@messenger.bus.commands'

    thn.shared.application.bus.add_command_bus_name_to_stamp_middleware:
        class: App\Shared\Infrastructure\Bus\AddBusNameToStampMiddleware
        arguments:
            - 'messenger.bus.commands'

    thn.shared.application.bus.doctrine_transaction_middleware:
        class: Symfony\Bridge\Doctrine\Messenger\DoctrineTransactionMiddleware
        arguments:
            - '@doctrine'
            - 'thn'

    ### Event Bus Configuration ###
    thn.shared.application.event_bus:
        class: App\Shared\Infrastructure\Bus\Event\MessengerEventBus
        arguments:
            - '@messenger.bus.events'

    thn.shared.application.bus.add_event_bus_name_to_stamp_middleware:
        class: App\Shared\Infrastructure\Bus\AddBusNameToStampMiddleware
        arguments:
            - 'messenger.bus.events'

    thn.shared.application.event_bus.handler_middleware:
        class: Symfony\Component\Messenger\Middleware\HandleMessageMiddleware
        arguments:
            - '@messenger.bus.events.messenger.handlers_locator'
            - true

    ### Query Bus Configuration ###
    thn.shared.application.query_bus:
        class: App\Shared\Infrastructure\Bus\Query\MessengerQueryBus
        arguments:
            - '@messenger.bus.queries'

    message.message_factory:
        class: App\Shared\Domain\Message\Factory\FullyQualifiedClassNameMessageFactory

    thn.shared.infrastructure.bus.event.add_amqp_stamp_middleware:
        class: App\Shared\Infrastructure\Bus\Event\AddAmqpStampMiddleware
